### PR TITLE
The issue of Evaluator

### PR DESCRIPTION
**Pull request by chiehpower**
As we knew, we sorted the order by confidence score before we computed between the detections and GT. 
In the `Evaluator.py`, currently the `det` variable only record whether it has seen or not. So if the higher confidence score of detection that it pass the IOU threshold, it will be counted as true positive. However, it cannot identify whether the IOU value of lower confidence score of detection is higher than that of previous one or not.  

For example, in your example from /aux_images/samples_1_v2.png, obviously the order of detection H is higher than that of detection G, but the IOU value of H is lower than that of G. 

In previous script, it didn't record the IOU value of detection H, so how it can know the other detections of  IOU value at the same GT whether it is higher than the flag which is as "seen" one.

### CODE REVIEW

**Comment by ShenWeihan** [comment]
Same problem. Wasted my whole day to find it. The function getCoordinatesType is never called in Evaluator which is weird.
Solved by stick to format=BBFormat.XYWH.

**Comment by ShenWeihan** [comment]
It's the way how PASCAL mAP is computed, by it's definition. What you said refers to COCO.

**Comment by rafaelpadilla** [comment]
See it this way: The detection with the highest confidence has priority over detections with lower confidences. 
Then the detection with the highest confidence will match the groundtruth that has the highest IOU.

**Comment by chiehpower** [comment]
Dear @rafaelpadilla, thanks for your reply! 
I really appreciate your contribution.

I understand "The detection with the highest confidence has priority over detections with lower confidences." and " the detection with the highest confidence will match the groundtruth that has the highest IOU if the IOU is higher than a threshold". 

I am sorry that my description of aforementioned example was not clear. 

New simple example:
photo_2020-12-14_15-03-33

What I mean is that suppose this situation, we can know the A which got the highest confidence score of detection among three detections, but the C got the highest IOU value among three detections so the C should be evaluated by True and the rest of two should be evaluated by False. Although A is higher than a threshold (as you said, Pascal uses 0.5 as the IOU threshold), the final computation should be C not A for matching with GT because the IOU value of C is higher than IOU value of A.

The current algorithm cannot guarantee the A which is the highest IOU value among three detections. We can see the `Evaluator.py` from line 111 to 117 that after pass the detection A, the det[dects[d][0]][jmax] will be 1. (The A is sorted before the C.)
So when the program is going to evaluate the detection C, it will directly go to **else**, right?

I am trying to elaborate my train of thought more clear, if there is any wrong, welcome to correct me.
Thank you so much!

BR,
Chieh

**Comment by rafaelpadilla** [comment]
Hi @chiehpower,

First, I took sometime to go over the code and I will try to explain step by step. 

I created the bounding boxes manually in an image (325x330) just to simulate your problem and debugged the code to see where the mistake might be. If you would like to replicate the code, you can create the bounding boxes below:

```
bb_A = BoundingBox('img_1', 0, (142, 152, 96, 95), CoordinatesType.ABSOLUTE, (325, 330), BBType.DETECTED, .8, format=BBFormat.XYWH)
bb_B = BoundingBox('img_1', 0, (164, 68, 69, 94), CoordinatesType.ABSOLUTE, (325, 330), BBType.DETECTED, .60, format=BBFormat.XYWH)
bb_C = BoundingBox('img_1', 0, (67, 168, 66, 69), CoordinatesType.ABSOLUTE, (325, 330), BBType.DETECTED, .50, format=BBFormat.XYWH)
bb_gt = BoundingBox('img_1', 0, (91, 103, 112, 108), CoordinatesType.ABSOLUTE, (325, 330), BBType.GROUND_TRUTH, 1., format=BBFormat.XYWH)
boundingboxes = BoundingBoxes()
boundingboxes.add_bounding_box(bb_A)
boundingboxes.add_bounding_box(bb_B)
boundingboxes.add_bounding_box(bb_C)
boundingboxes.add_bounding_box(bb_gt)

evaluator = Evaluator()
metricsPerClass = evaluator.get_pascal_voc_metrics(
    boundingboxes, 
    IOU_threshold=0.5, 
    method=MethodAveragePrecision.EVERY_POINT_INTERPOLATION) 

```
To make this representation follow your IOUs, you manually replace the iou by 0.55 for detection A when it reaches [Evaluator.py Line 107](https://github.com/rafaelpadilla/Object-Detection-Metrics/blob/master/lib/Evaluator.py#L107).

Now some points you need to have in mind:

1) `det` is a Counter created [here](https://github.com/rafaelpadilla/Object-Detection-Metrics/blob/master/lib/Evaluator.py#L94) containing all images in the dataset and their respective amount of ground-truths in an array. 

For example: if image img_0 has 3 groundtruths, `det` would be: `{'img_1': array([0., 0., 0.])}`

In your example, the object `det` is: `{'img_1': array([0])}`, as it only has 1 image, as seen below:
image


2) Seen that, let's move to the loop at [line 99](https://github.com/rafaelpadilla/Object-Detection-Metrics/blob/master/lib/Evaluator.py#L99). Note that it will loop through all detections ordered by confidence. Therefore, the first one is detection A (the highest confidence), which has IOU=0.55. Loop at [Line 104](https://github.com/rafaelpadilla/Object-Detection-Metrics/blob/master/lib/Evaluator.py#L104) is executed only once, because there is only 1 groundtruth.

3) When code reaches [line 111](https://github.com/rafaelpadilla/Object-Detection-Metrics/blob/master/lib/Evaluator.py#L111) we have `iouMax` => `0.55` and `jmax` => `0`

4) [Line 112](https://github.com/rafaelpadilla/Object-Detection-Metrics/blob/master/lib/Evaluator.py#L112) we have:

`dects[d][0]` => `'img_1'` 

`det[dects[d][0]]` => `det['img_1']`  => `array([0.])`

Therefore `det[dects[d][0]][jmax]` is the same as `det['img_1'][0]` which is equals to `0`, instead of `1` as you mentioned. See below:
image

So it will not execute the `else` at line 116. Being so, detection A will be set as TP.

I hope it was clear. You can follow all these steps debugging the code.

Best regards,
Rafael

**Comment by chiehpower** [comment]
Thanks for your detail explanation! It is very clear.

My concern actually is the code how to deal with **the lower confidence score detection with higher IOU value**.  

Let me clarify this sentence again.
>The current algorithm cannot guarantee the A which is the highest IOU value among three detections. We can see the Evaluator.py from line 111 to 117 that after pass the detection A, the det[dects[d][0]][jmax] will be 1. (The A is sorted before the C.)

As you mentioned, `det[dects[d][0]]` => `det['img_1']` => `array([0.])`. 
Also, `det[dects[d][0]][jmax]` => `det['img_1'][0]` => `0`, and it will be set by 1 to flag as already **seen** at [line 114](https://github.com/rafaelpadilla/Object-Detection-Metrics/blob/master/lib/Evaluator.py#L114). (Now `det[dects[d][0]][jmax]` => 1 that is what I mentioned "will be 1" meaning.) Of course, it will not execute the else at line 116, detection A will be set as TP.
Above is the detection A process. Your explanation was also clear until this part.

Let's go to `Detection C` which gets higher IOU value than `Detection A`.
The IOU value of Detection C is 65%, so obviously it can pass the [line 111](https://github.com/rafaelpadilla/Object-Detection-Metrics/blob/master/lib/Evaluator.py#L111); however, it cannot execute the [line 112](https://github.com/rafaelpadilla/Object-Detection-Metrics/blob/master/lib/Evaluator.py#L112) because now `det[dects[d][0]][jmax]` is equal to 1, so it will directly execute the `else` stage at [line 116](https://github.com/rafaelpadilla/Object-Detection-Metrics/blob/master/lib/Evaluator.py#L116) and then `Detection C` will be set as FP. In fact, `Detection C` should be set by TP because its IOU is higher than `Detection A`.

In the original code, it cannot handle these parts below:
1. The code can only record "it already seen", but it cannot remember the IOU value of what it saw. See, it just knew the detection A is higher than IOU threshold, but it didn't know what the IOU value of detection A is. How does it know the other detections whether their IOU values are higher than previous (i.e., seen) one or not?  (If the code can handle this part, could you point out? Thank you.)

2. **SUPPOSE** even it can know the detection of lower confidence score which gets higher IOU value than previous one, it cannot change it to the detection of getting higher IOU in original code, and it cannot set TP to FP if the detection of higher confidence score with lower IOU value.

Honestly, I think these two points are quite critical. 
Thank you for your kind discussion!

Sincerely,
Chieh

**Comment by rafaelpadilla** [comment]
@chiehpower 

I understand your concerns. But the assessment rule is clear: One groundtruth can only be associated once with a detection. That's why detection A is TP and all other detections overlapping the groundtruth will be FP. It makes total sense to me. It is like those games that you gotta tell which target you are trying to hit before shooting. Once the target is hit, it is out of the game and no other shot can hit it again.

The tag it "has already seen" is what identifies if the target is hit making it out of the game. And, if it is out of the game, groundtruth cannot be hit again. The criterion to hit the target is only one: IOU > Threshold. So, it does not have to remember the IOU of the detection that hit it. Why should it be remembered? It makes sense to me that way. The PASCAL criteria is implemented that way. And so is our code. Our code does not remember the IOU that hit the target.

An analogy: 5 kids (A, B, C, D, E) have rocks and have to throw them at some glass bottles. Each turn, one kid at a time will choose a bottle and will throw 1 rock. The criteria to determine if the kid scores a point is that rock must break the bottle. The oldest kids start first.

In this example: each rock thrown is a detection; the age of the kid is the confidence which determines who throws first; the criterion to destroy the bottle is the IOU threshold; 

Comparing this example to your questions: it does not make sense to consider a second shot in a bottle that was already destroyed. If some kid hits a rock in a already broken bottle, it makes no sense to question "how well was the shot that destroyed that bottle".  No comparison with previous shots have to be made.

**Comment by chiehpower** [comment]
Dear @rafaelpadilla ,

Thanks for your explanation! 
According to your description, it completely makes sense to me. That's about the definition.

Actually before I had another question that I read the [example](https://github.com/rafaelpadilla/Object-Detection-Metrics#an-ilustrated-example) of your README tutorial, we could see the upper right GT of Image 3 which can match with three detections (i.e., G, H, I).
chrome_7GbVSj30U1
The confidence scores of G, H, I are 18%, 67%, 38%, respectively.
The IOU of G is obviously larger than the others. Hence, we can see [this tabular](https://github.com/rafaelpadilla/Object-Detection-Metrics/raw/master/aux_images/table_2_v2.png) which shows the lower confidence score of G is TP. So what the critical reason of I misunderstood is because the IOU values of H and I are not over the IOU threshold. That's why G can be set as TP.

If we set a lower IOU threshold (like only 10%), H will be set as TP, and then G and I will be set as FP.

OK. I totally got it. 

Thank you for your enlightenment. 

Best regards,
Chieh

**Comment by rafaelpadilla** [comment]
@chiehpower 

Exactly! It is all about the definition. 

In this last example you pointed out perfectly. Event hough H has the highest priority to match with the groundtruth, its IOU is lower than the threshold (set as 0.3 for this example). Then detection I tries to match with the groundtruth, but the same situation occurs: its IOU is lower than the threshold. Then it remains detection G, which matches with groundtruth because its IOU is higher than the preset threshold.

And you concluded correctly.... If we reduce the IOU threshold, detection I will be set as TP, while G and H will be FP.

Best regards,
Rafael

**Pull request closed without merging**
